# docker-compose.yml
version: '3'
services:
  validator:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
      - ./logs:/app/logs
    restart: unless-stopped
